# Bayes Estimator

### <font color='orange'>Universidad Autónoma de Yucatán</font> _Facultad de Matemáticas_

**Teacher:** Dr. Arturo Espinosa Romero <[eromero@correo.uady.mx](mailto:eromero@correo.uady.mx)>

**Student:** Ing. Dayan Bravo Fraga <[dayan3847@gmail.com](mailto:dayan3847@gmail.com)>

# Practice 5:  Kalman Filter for Ball Tracking

## GitHub: [Practice 5](https://github.com/dayan3847/bayes_estimator/tree/main/practice5-ball_tracking)

In [19]:
import sympy as sp
import numpy as np

In [3]:
# sp.init_printing(use_unicode=True)

In [4]:
#@title Variables:
X, Y, Z = sp.symbols("X Y Z")  # Coordenadas en metros
R = sp.Symbol('R')  # Radio en metros
Xp = sp.Symbol(r'\dot{X}')
Yp = sp.Symbol(r'\dot{Y}')
Zp = sp.Symbol(r'\dot{Z}')
dt = sp.Symbol(r'\Delta t')

In [5]:
# @title "X" Estado
XX = sp.Matrix([
    [X],
    [Y],
    [Z],
    [Xp],
    [Yp],
    [Zp],
])

sp.Eq(sp.Symbol(r'\mathbb{X}'), XX, evaluate=False)

Eq(\mathbb{X}, Matrix([
[      X],
[      Y],
[      Z],
[\dot{X}],
[\dot{Y}],
[\dot{Z}]]))

In [6]:
# @title "Z" Medicion
ZZ = sp.Matrix([
    [X],
    [Y],
    [Z],
    [R],
])
sp.Eq(sp.Symbol(r'\mathbb{Z}'), ZZ, evaluate=False)

Eq(\mathbb{Z}, Matrix([
[X],
[Y],
[Z],
[R]]))

In [7]:
# @title Funcion h
h_xz = sp.Matrix([
    [X / Z],
    [Y / Z],
    [(Xp + X * Zp) / Z],
    [(Yp + Y * Zp) / Z],
    [R / Z],
])
sp.Eq(sp.Function('h')(X, Z), h_xz, evaluate=False)

Eq(h(X, Z), Matrix([
[                    X/Z],
[                    Y/Z],
[(X*\dot{Z} + \dot{X})/Z],
[(Y*\dot{Z} + \dot{Y})/Z],
[                    R/Z]]))

In [12]:
# @title Matriz H es el Jacobian de h respecto al estado
HH = h_xz.jacobian(XX)
sp.Eq(sp.Symbol(r'\mathbb{H}x'), HH, evaluate=False)

Eq(\mathbb{H}x, Matrix([
[      1/Z,         0,                     -X/Z**2,   0,   0,   0],
[        0,       1/Z,                     -Y/Z**2,   0,   0,   0],
[\dot{Z}/Z,         0, -(X*\dot{Z} + \dot{X})/Z**2, 1/Z,   0, X/Z],
[        0, \dot{Z}/Z, -(Y*\dot{Z} + \dot{Y})/Z**2,   0, 1/Z, Y/Z],
[        0,         0,                     -R/Z**2,   0,   0,   0]]))

In [9]:
# @title Matriz A
AA = sp.Matrix([
    [1, 0, 0, dt, 0, 0],
    [0, 1, 0, 0, dt, 0],
    [0, 0, 1, 0, 0, dt],
    [0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 1],
])
sp.Eq(sp.Symbol(r'\mathbb{A}'), AA, evaluate=False)

Eq(\mathbb{A}, Matrix([
[1, 0, 0, \Delta t,        0,        0],
[0, 1, 0,        0, \Delta t,        0],
[0, 0, 1,        0,        0, \Delta t],
[0, 0, 0,        1,        0,        0],
[0, 0, 0,        0,        1,        0],
[0, 0, 0,        0,        0,        1]]))

In [13]:
#@title Matriz de calibracion.
K_cam = sp.Matrix([
    [1.3778036814997304e+03, 0, 4.0002681782947193e+02],
    [0, 1.3778036814997304e+03, 3.00096061319675721e+02],
    [0, 0, 1],
])
sp.Eq(sp.Symbol('K'), K_cam, evaluate=False)

Eq(K, Matrix([
[1377.80368149973,                0, 400.026817829472],
[               0, 1377.80368149973, 300.096061319676],
[               0,                0,                1]]))

In [14]:
#@title Matriz de calibracion (inversa)
K_cam_inv = K_cam.inv()
sp.Eq(sp.Symbol('K^{-1}'), K_cam_inv, evaluate=False)

Eq(K^{-1}, Matrix([
[0.000725792805918116,                    0, -0.290336586554948],
[                   0, 0.000725792805918116, -0.217807562390183],
[                   0,                    0,                  1]]))

In [18]:
# imprimir la innversa de K en formato de numpy
print(np.array(K_cam_inv).astype(np.float64))

[[ 7.25792806e-04  0.00000000e+00 -2.90336587e-01]
 [ 0.00000000e+00  7.25792806e-04 -2.17807562e-01]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
