# Bayes Estimator

### <font color='orange'>Universidad Autónoma de Yucatán</font> _Facultad de Matemáticas_

**Teacher:** Dr. Arturo Espinosa Romero <[eromero@correo.uady.mx](mailto:eromero@correo.uady.mx)>

**Student:** Ing. Dayan Bravo Fraga <[dayan3847@gmail.com](mailto:dayan3847@gmail.com)>

# Practice 6:  Kalman Filter for a Conic

## GitHub: [Practice 6](https://github.com/dayan3847/bayes_estimator/tree/main/practice6-kf_conic)

In [1]:
import sympy as sp

In [2]:
# sp.init_printing(use_unicode=True)

In [19]:
#@title Variables:
A, B, C, D, E, F = sp.symbols("A B C D E F")
X, Y = sp.symbols("X Y")

In [21]:
# @title "X" Estado
XX = sp.Matrix([
    [A],
    [B],
    [C],
    [D],
    [E],
    [F],
])
sp.Eq(sp.Symbol(r'\mathbb{X}'), XX, evaluate=False)

Eq(\mathbb{X}, Matrix([
[A],
[B],
[C],
[D],
[E],
[F]]))

In [22]:
# @title "Z" Medicion
x, y = sp.symbols("x y")
ZZ = sp.Matrix([
    [X],
    [Y],
])
sp.Eq(sp.Symbol(r'\mathbb{Z}'), ZZ, evaluate=False)

Eq(\mathbb{Z}, Matrix([
[X],
[Y]]))

In [40]:
h_xz = sp.Matrix([
    [A * X ** 2 + B * Y ** 2 + C * X * Y + D * X + E * Y + F],
])
sp.Eq(
    sp.Eq(
        sp.Function('h')(sp.Symbol('\mathbb{X,Y}'), evaluate=False),
        h_xz, evaluate=False
    ),
    sp.Symbol('\emptyset'), evaluate=False
)

Eq(Eq(h(\mathbb{X,Y}), Matrix([[A*X**2 + B*Y**2 + C*X*Y + D*X + E*Y + F]])), \emptyset)

In [34]:
sp.Eq(
    sp.MatMul(
        sp.Matrix([X, Y, 1]).T,
        sp.Matrix([
            [A, C / 2, D / 2],
            [C / 2, B, E / 2],
            [D / 2, E / 2, F],
        ]),
        sp.Matrix([X, Y, 1]),
        evaluate=False),
    sp.Matrix([0]), evaluate=False
)

Eq(Matrix([[X, Y, 1]])*Matrix([
[  A, C/2, D/2],
[C/2,   B, E/2],
[D/2, E/2,   F]])*Matrix([
[X],
[Y],
[1]]), Matrix([[0]]))

In [38]:
sp.Eq(
    sp.expand(
        sp.MatMul(
            sp.Matrix([X, Y, 1]).T,
            sp.Matrix([
                [A, C / 2, D / 2],
                [C / 2, B, E / 2],
                [D / 2, E / 2, F],
            ]),
            sp.Matrix([X, Y, 1]),
            evaluate=True),
    ),
    sp.Matrix([0]), evaluate=False
)

Eq(Matrix([[A*X**2 + B*Y**2 + C*X*Y + D*X + E*Y + F]]), Matrix([[0]]))

In [41]:
# @title Jacobiano de h(X,Z) con respecto a X
HH = h_xz.jacobian(XX)
sp.Eq(sp.Symbol(r'\mathbb{H}'), HH, evaluate=False)

Eq(\mathbb{H}, Matrix([[X**2, Y**2, X*Y, X, Y, 1]]))

In [42]:
# @title Jacobiano de h(X,Z) con respecto a Z
JJ = h_xz.jacobian(ZZ)
sp.Eq(sp.Symbol(r'\mathbb{J}'), JJ, evaluate=False)

Eq(\mathbb{J}, Matrix([[2*A*X + C*Y + D, 2*B*Y + C*X + E]]))

In [9]:
# encontrar la matrix nula de XX (que multiplica a XX y da 0) 
MM =

[]

In [13]:
import numpy as np

x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [14]:
A = np.outer(x, x)
A

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [17]:
A @ x

array([14, 28, 42])