# Bayes Estimator

### <font color='orange'>Universidad Autónoma de Yucatán</font> _Facultad de Matemáticas_

**Teacher:** Dr. Arturo Espinosa Romero <[eromero@correo.uady.mx](mailto:eromero@correo.uady.mx)>

**Student:** Ing. Dayan Bravo Fraga <[dayan3847@gmail.com](mailto:dayan3847@gmail.com)>

# Practice 6:  Kalman Filter for a Conic

## GitHub: [Practice 6](https://github.com/dayan3847/bayes_estimator/tree/main/practice6-kf_conic)

In [22]:
import sympy as sp

In [2]:
# sp.init_printing(use_unicode=True)

In [23]:
#@title Variables:
A, B, C, D, E, F = sp.symbols("A B C D E F")
X, Y = sp.symbols("X Y")

In [24]:
# @title Ecuacion de una conica
# h(X,Z)
eq = sp.Eq(
    A * X ** 2 + B * Y ** 2 + C * X + D * Y + E * X * Y + F,
    0,
    evaluate=False
)
eq

Eq(A*X**2 + B*Y**2 + C*X + D*Y + E*X*Y + F, 0)

In [25]:
h_xz = sp.Matrix([
    [A * X ** 2 + B * Y ** 2 + C * X + D * Y + E * X * Y + F],
])
h_xz
# sp.Eq(sp.Function('h')(sp.Symbol('\mathbb{X}'), h_xz, evaluate=False))

Matrix([[A*X**2 + B*Y**2 + C*X + D*Y + E*X*Y + F]])

In [28]:
# @title Jacobiano de h(X,Z) con respecto a X
HH = h_xz.jacobian(XX)
HH

Matrix([[X**2, Y**2, X, Y, X*Y, 1]])

In [31]:
# @title Jacobiano de h(X,Z) con respecto a Z
JJ = h_xz.jacobian(ZZ)
JJ

Matrix([[2*A*X + C + E*Y, 2*B*Y + D + E*X]])

In [26]:
# @title "X" Estado
XX = sp.Matrix([
    [A],
    [B],
    [C],
    [D],
    [E],
    [F],
])
sp.Eq(sp.Symbol(r'\mathbb{X}'), XX, evaluate=False)

Eq(\mathbb{X}, Matrix([
[A],
[B],
[C],
[D],
[E],
[F]]))

In [30]:
# @title "Z" Medicion
x, y = sp.symbols("x y")
ZZ = sp.Matrix([
    [X],
    [Y],
])
sp.Eq(sp.Symbol(r'\mathbb{Z}'), ZZ, evaluate=False)

Eq(\mathbb{Z}, Matrix([
[X],
[Y]]))

In [9]:
# encontrar la matrix nula de XX (que multiplica a XX y da 0) 
MM = 

[]

In [13]:
import numpy as np
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [14]:
A = np.outer(x, x)
A

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [17]:
A @ x

array([14, 28, 42])